### ISSUE TITLE
Challenges when following Getting Started guide

### ISSUE THREAD

**Issue by ps003** [VMwareFusion/nautilus#6] opened 2020-02-24 20:14 UTC
Hello - I'm following the instructions here - https://github.com/VMwareFusion/nautilus/blob/master/docs/getting-started.md
and having some issues. I did a quick screen recording - here is a link to the recording on Youtube.

https://youtu.be/En7l2-MnTkU - It looks like it's still converting to HD, so here's a screenshot as well.

![nautilus issue](https://user-images.githubusercontent.com/5438258/75187498-c0dc2400-570f-11ea-8901-c75650215004.jpg)

I'm able to download the image, but unable to successfully run the container. You can watch the entire process in the video, and the screenshot shows the same iterm window used in the video. Thx for the assistance. I'll do anything needed to help troubleshoot.

**Comment by mikeroySoft** [comment] 2020-02-24 22:16
Looks like the same issue as reported here:
https://github.com/VMwareFusion/nautilus/issues/4

**Comment by mikeroySoft** [comment] 2020-03-05 00:03
duplicate of #4

**Closed** 2020-03-05 00:02 UTC
